from django.db import models

# Create your models here.


class Day(models.Model):
    date = models.DateField(auto_now=False, auto_now_add=False)
    food_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    beverage_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    liquor_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    beer_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    wine_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    net_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    forecast = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    last_year = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    vs_lastyear = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    WTD_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    WTD_budget = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    WTD_sales_last_year = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    week_vs_lastyear = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    LBW_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    liquor_mix = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    foh_actual = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    foh_target = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    foh_variance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    boh_actual = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    boh_target = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    boh_variance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_2 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_11 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_6 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_4 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_7 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    comp_8 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    takeaway_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    takeaway_percentage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deliveries_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    headwait = models.CharField(max_length=200)
    drop_variance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    managers = models.CharField(max_length=200)
    food_harvest = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    TCI_percentage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    TCI_variance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    lunch_sales = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    pc_drawer = models.DecimalField(max_digits=10, decimal_places=2, default=0)
